# framework defined properties
spring:
    application:
        name: flight-engine

vaadin:
    whitelisted-packages: com.vaadin,org.vaadin,com.github.appreciated.apexcharts
    devmode:
        devTools:
            enabled: false

# user defined properties
grid-column-provider:
    date-format: 'dd-MM-yyyy hh:mm a'